service_name: {{ cookiecutter.project_name }}-service
paseto:
  token_symetric_key: 12345678901234567890123456789012
  token_duration: 24h
observability:
  debugger_key: '6548973'
  jaeger: 
    dial_hostname: localhost:4317
  sensitive_paths:
    - "/accounts"
  ignored_paths:
    - "/metrics"
db:
  hostname: {{ cookiecutter.postgres_hostname }}
  port: {{ cookiecutter.postgres_port }}
  username: {{ cookiecutter.postgres_user }}
  password: {{ cookiecutter.postgres_password }}
  database: {{ cookiecutter.project_name }}_db
  ssl: disable
