service_name: {{ cookiecutter.project_name }}-service
paseto:
  token_symetric_key: 12345
  token_duration: 24h
observability:
  jaeger: 
    dial_hostname: localhost:4317
    ignored_paths:
      - "/metrics"
db:
  hostname: {{ cookiecutter.postgres_hostname }}
  port: {{ cookiecutter.postgres_port }}
  username: {{ cookiecutter.postgres_user }}
  password: {{ cookiecutter.postgres_password }}
  database: {{ cookiecutter.project_name }}_db
  ssl: disable
