services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER={{cookiecutter.postgres_user}}
      - POSTGRES_PASSWORD={{cookiecutter.postgres_password}}
      - POSTGRES_DB={{cookiecutter.postgres_db}}
    ports:
      - "{{cookiecutter.postgres_port}}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c ssl=off

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://{{cookiecutter.postgres_user}}:{{cookiecutter.postgres_password}}@postgres:{{cookiecutter.postgres_port}}/{{cookiecutter.postgres_db}}?sslmode=disable
    depends_on:
      - postgres

  prometheus:
    build:
      context: ./dockerfiles/prometheus
      dockerfile: Dockerfile.dev
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      # - ./dockerfiles/grafana/dashboards:/var/lib/grafana/dashboards
      - ./dockerfiles/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  jaeger:
    image: jaegertracing/jaeger:2.3.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

volumes:
  postgres_data:
    driver: local
