services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      - POSTGRES_USER=cookie_user
      - POSTGRES_PASSWORD=cookie_pwd
      - POSTGRES_DB=cookiecutter_dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c ssl=off

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    platform: linux/amd64
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_URI=postgres:5432
      - DATA_SOURCE_USER=cookie_user
      - DATA_SOURCE_PASS=cookie_pwd
    depends_on:
      - postgres

  prometheus:
    build:
      context: ./dockerfiles/prometheus
      dockerfile: Dockerfile.dev
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./dockerfiles/grafana/files/dashboards:/var/lib/grafana/dashboards
      - ./dockerfiles/grafana/files/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  jaeger:
    image: jaegertracing/jaeger:2.3.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

volumes:
  postgres_data:
    driver: local
