{
 "title": "cookiecutter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(request_total[5m])*1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    { "expr": "request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method) (uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(uri_request_total[5m]) * 300)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request average by uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(request_duration_sum[5m])) / sum by (uri) (rate(request_duration_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests (200) by uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(uri_request_total{code=\"200\"}[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request failures by uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(uri_request_total{code!=\"200\"}[5m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } }
 ]
}