
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "accounts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "role_id" INTEGER not null default(1),
  "is_active" BOOLEAN DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "updated_at" TIMESTAMP NOT NULL DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) UNIQUE NOT NULL

);

CREATE TABLE "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "role_permissions" (
  "role_id" INTEGER NOT NULL,
  "permission_id" INTEGER NOT NULL,
  CONSTRAINT "fk_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id"),
  CONSTRAINT "fk_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id")
)
